package model

import "github.com/gofrs/uuid"

// Lock is a pair of resource and token to release it.
type Lock struct {
	// ResourceID is a unique identifier of a Lock.
	resourceID string `validate:"required,base64"`
	// Token is a secret you can use to unlock the resource.
	token uuid.UUID `validate:"required"`
}

// NewLock creates a new Lock.
func NewLock(rID, t string) (*Lock, error) {
	tkn, err := uuid.FromString(t)
	if err != nil {
		return nil, err
	}
	return &Lock{
		resourceID: rID,
		token:      tkn,
	}, nil
}

// NewLockWithToken creates a new Lock with autogenerated token field.
func NewLockWithToken(rID string) (*Lock, error) {
	t, err := uuid.NewV4()
	if err != nil {
		return nil, err
	}
	return &Lock{
		resourceID: rID,
		token:      t,
	}, nil
}

func (l Lock) ResourceID() string {
	return l.resourceID
}

func (l Lock) Token() string {
	return l.token.String()
}
