sequenceDiagram
  autonumber
  participant w as Worker
  participant lm as LockManager
  participant ls as LockStorage

  w->>+lm: lock(resourceID)
  lm->>lm: secretKey = randomUUID()
  lm->>lm: lock = Lock(resourceID, secretKey)
  lm->>+ls: create(lock)
  alt lock is already in LockStorage
    rect rgba(255, 0, 0, 0.5)
      ls-->>lm: ErrLockAlreadyExists
      lm-->>w: _
      Note over w,lm: HTTP: 409::Conflict<br>GRPC: 6::ALREADY_EXISTS
    end
  end
  ls-->>-lm: _
  lm-->>-w: secretKey
  Note over w,lm: HTTP: 201::Created<br>GRPC: 0::OK
