sequenceDiagram
  autonumber
  participant w as Worker
  participant lm as LockManager
  participant ls as LockStorage

  w->>+lm: unlock(resourceID, token)
  lm->>+ls: deleteIfTokenMatches(lock)
  alt lock is not found
    rect rgba(255, 0, 0, 0.5)
      ls-->>lm: ErrLockNotFound
      lm-->>w: _
      Note over w,lm: HTTP: 404::Not Found<br>GRPC: 5::NOT_FOUND
    end
  end
  alt token doesn't match the one that is already in the LockStorage
    rect rgba(255, 0, 0, 0.5)
      ls-->>lm: ErrInvalidToken
      lm-->>w: _
      Note over w,lm: HTTP: 400::Bad Request<br>GRPC: 3::INVALID_ARGUMENT
    end
  end
  ls-->>-lm: _
  lm-->>-w: _
  Note over w,lm: HTTP: 200::OK<br>GRPC: 0::OK
