exclude: ^docs/gen/
repos:
  # pre-commit install
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key

  # pre-commit install
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.7
    hooks:
      - id: typos
        args: [--exclude=go.mod, --exclude=go.sum]

  # pre-commit install --hook-type commit-msg
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        name: conventional-commits
        alias: conventional-commits
        stages: [commit-msg]
        args:
          [
            build,
            chore,
            ci,
            deploy,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
          ]

  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
        name: go-mod
        alias: go-mod
        exclude: tools|wire_gen.go|mock
      - id: go-fumpt
        name: go-fumpt
        alias: go-fumpt
        exclude: tools|wire_gen.go|mock
      - id: my-cmd
        name: goimports-reviser
        alias: goimports-reviser
        exclude: tools|wire_gen.go|mock
        args: [goimports-reviser, .]
      - id: my-cmd
        name: golines
        alias: golines
        exclude: tools|wire_gen.go|mock
        args: [golines, ., -w]
