version: "3"

vars:
  MOCKERY_CONFIG_FILE: .config/.mockery.yaml
  GOIMPORTS_REVISER_COMPANY_PREFIXES:

tasks:
  lint:golangci:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: cd {{.GO_SRC_PATH}} && golangci-lint run

  lint:goimports-reviser:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
      COMPANY_PREFIXES: '{{default "" .GOIMPORTS_REVISER_COMPANY_PREFIXES}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: GO_SRC_PATH={{.GO_SRC_PATH}} COMPANY_PREFIXES={{.COMPANY_PREFIXES}} ./script/goimports-reviser.sh

  lint:gofumpt:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: gofumpt -l -w -extra {{.GO_SRC_PATH}}

  lint:golines:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: golines -w {{.GO_SRC_PATH}}

  lint:go-vet:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: go vet {{.GO_SRC_PATH}}/...

  lint:
    deps:
      - "lint:golangci"
      - "lint:goimports-reviser"
      - "lint:gofumpt"
      - "lint:go-vet"
      - "lint:golines"

  gen:wire:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*wire.go"
    cmd: wire gen {{.GO_SRC_PATH}}/...

  gen:mockery:
    vars:
      GO_SRC_PATH: '{{default "." .GO_SRC_PATH}}'
      CONFIG_FILE: '{{default "" .MOCKERY_CONFIG_FILE}}'
    sources:
      - "{{.GO_SRC_PATH}}/**/*.go"
    cmd: GO_SRC_PATH={{.GO_SRC_PATH}} CONFIG_FILE={{.CONFIG_FILE}} ./script/mockery.sh

  gen:
    deps:
      - "gen:wire"
      - "gen:mockery"
