version: "3.9"

services:
  lock-manager:
    container_name: lock-manager
    build:
      context: "../../"
      dockerfile: "./Dockerfile"
    depends_on: ["storage"]
    restart: "always"
    expose: [8082, 8084]
    ports: ["8082:8082", "8084:8084"]

  storage:
    expose:
      - 9090
