package model

import (
	"github.com/google/uuid"
)

// Lock is a pair of resource and token to release it.
type Lock struct {
	// ResourceID is a unique identifier of a Lock.
	ResourceID string
	// Token is a secret you can use to unlock the resource.
	Token string
}

// NewLock creates a new Lock.
func NewLock(resourceID, token string) Lock {
	return Lock{
		ResourceID: resourceID,
		Token:      token,
	}
}

// NewLockWithToken creates a new Lock with autogenerated token field.
func NewLockWithToken(resourceID string) Lock {
	return NewLock(resourceID, uuid.New().String())
}
