storage:
  redis:
    uri: "localhost:9090"
    db: 0
    username:
    password:

handler:
  grpc:
    port: "8082"
    withReflection: true
    ping:
      after: 10m
      timeout: 15s
    conn:
      maxIdle: 5m
      maxAge: 5m
  http:
    port: "8084"
    prefork: false
    concurrency: 262144
    disableKeepAlive: false
    readTimeout: 5s
    writeTimeout: 5s
    idleTimeout: 10s

metric:
  pull:
    port: "8086"
    readTimeout: 5s

application:
  environment: "dev"
  version: "v0.1.0"
