repository:
  redis:
    uri: "storage:6379"
    db: 0
    username:
    password:

handler:
  grpc:
    port: "8082"
    withReflection: true
    ping:
      after: 10m
      timeout: 15s
    conn:
      maxIdle: 5m
      maxAge: 5m

observability:
  pull:
    metric:
      port: "8084"
      readTimeOut: 5s

application:
  environment: "dev"
  version: "v0.1.0"
