repository:
  redis:
    uri: "localhost:6379"
    db: 0
    username:
    password:

handler:
  grpc:
    ip: "localhost"
    port: "8082"

service:
  resourceID:
    maxLength: 32
    minLength: 32
