repository:
  redis:
    uri: "localhost:9090"
    db: 0
    username:
    password:

handler:
  grpc:
    port: "8082"
    withReflection: true
    ping:
      after: 10m
      timeout: 15s
    conn:
      maxIdle: 5m
      maxAge: 5m

service:
  resourceID:
    maxLength: 32
    minLength: 32

observability:
  pull:
    metric:
      port: "8084"
      readTimeOut: 5s

application:
  environment: "local"
  version: "v0.1.0"
