all: false
quiet: true
disable-version-string: true
with-expecter: true
case: underscore
outpkg: "{{.PackageName}}mock "
filename: '{{trimSuffix .InterfaceNameSnake "_i"}}.go'
dir: "{{.InterfaceDir}}/mock"
mockname: '{{trimSuffix .InterfaceName "I"}}'
packages:
  github.com/ruslanSorokin/lock-manager/internal/lock-manager/provider:
    interfaces:
      LockProviderI:
  github.com/ruslanSorokin/lock-manager/internal/lock-manager/service:
    interfaces:
      LockServiceI:
  github.com/ruslanSorokin/lock-manager/internal/lock-manager/metric:
    interfaces:
      ServiceMetricI:
  github.com/ruslanSorokin/lock-manager/internal/pkg/util/app:
    interfaces:
      MetricI:
  github.com/ruslanSorokin/lock-manager/internal/pkg/util/grpc:
    interfaces:
      RecoveryMetricI:
