version: "3"

tasks:
  install-golines:
    cmd: go install github.com/segmentio/golines@latest
    status:
      - "which golines"

  install-gofumpt:
    cmd: go install mvdan.cc/gofumpt@latest
    status:
      - "which gofumpt"

  install-goimports-reviser:
    cmd: go install github.com/incu6us/goimports-reviser/v3@latest
    status:
      - "which goimports-reviser"

  install-wire:
    cmd: go install github.com/google/wire/cmd/wire@latest
    status:
      - "which wire"

  install-golangci-lint:
    cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - "which golangci-lint"

  install-tools:
    deps:
      - "install-golines"
      - "install-gofumpt"
      - "install-goimports-reviser"
      - "install-wire"
      - "install-golangci-lint"
