version: "3"

tasks:
  download-tools: go mod download

  install-golines:
    deps: ["download-tools"]
    cmd: go install github.com/segmentio/golines
    status:
      - "which golines"

  install-gofumpt:
    deps: ["download-tools"]
    cmd: go install mvdan.cc/gofumpt
    status:
      - "which gofumpt"

  install-goimports-reviser:
    deps: ["download-tools"]
    cmd: go install github.com/incu6us/goimports-reviser/v3
    status:
      - "which goimports-reviser"

  install-wire:
    deps: ["download-tools"]
    cmd: go install github.com/google/wire/cmd/wire
    status:
      - "which wire"

  install-golangci-lint:
    deps: ["download-tools"]
    cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint
    status:
      - "which golangci-lint"

  install-tools:
    deps:
      - "install-golines"
      - "install-gofumpt"
      - "install-goimports-reviser"
      - "install-wire"
      - "install-golangci-lint"
