name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: "stable"

jobs:
  go-deps-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for missing dependencies
        run: |
          go mod tidy
          git diff --exit-code

      - name: Download dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['stable']

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: go build -v ./...
