name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  go-deps-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Check for missing dependencies
        run: |
          go mod tidy
          git diff --exit-code

      - name: Download dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Build code
        run: go build -v ./...
