name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: "1.20"

jobs:
  go-mod-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [go mod tidy]
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run [go mod download]
        run: |
          go mod download

      - name: Run [go mod verify]
        run: |
          go mod verify

  go-generate-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [go generate]
        run: |
          go generate ./...
          git diff --exit-code

  docs-generate-diff:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run [make docs.generate]
        run: |
          make docs.generate
          git diff --exit-code docs

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code
        run: go build -v ./...
