name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  GO_VERSION: 1.21

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run go fmt
        run: |
          go fmt ./...
          git diff --exit-code

  go-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run go vet
        run: |
          go vet ./...

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run typos
        uses: crate-ci/typos@v1.16.10
        with:
          config: .config/.typos.toml

  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        hook_aliases:
          [
            trailing-whitespace,
            end-of-file-fixer,
            check-yaml,
            detect-private-key,
            goimports-reviser,
            go-fumpt,
            golines,
          ]
    steps:
      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go-task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: task pre-commit:install-tools
        working-directory: ci

      - name: Run ${{ matrix.hook_aliases }}
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: ${{ matrix.hook_aliases }} --all-files
