name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Build code
        run: go build -v ./...

      - name: Run unit tests
        run: make app.unit-test

      - name: Run all tests
        run: make app.test
